version: 0.1.6a+{build}
image:
  - Visual Studio 2019
  - Previous Ubuntu1604
  - macOS

# note: on macOS the binary is built using Python 3.7 (installed via Homebrew), because
# the shipped Python lacks libraries PyInstaller needs.
stack: python 3.6

# note: 32 bit linux binary is build using docker
for:
  - matrix:
      only:
        - image: Previous Ubuntu1604

    services:
      - docker

environment:
  PY_DIR: C:\Python36-x64

init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

build: off

artifacts:
  - path: "dist\\accordably-win-i686.exe"
    name: "accordably-win-i686.exe"
  - path: "dist\\accordably-win-x86_64.exe"
    name: "accordably-win-x86_64.exe"
  - path: "dist\\accordably-linux-i686"
    name: "accordably-linux-i686"
  - path: "dist\\accordably-linux-x86_64"
    name: "accordably-linux-x86_64"
  - path: "dist\\accordably-macos-x86_64"
    name: "accordably-macos-x86_64"

install:
  - "python --version"
  - "python appveyor.py install"

test_script:
  - "python appveyor.py test"
  - "python appveyor.py dist"


deploy:
  - provider: GitHub
    description: 'Accordably Binary Release'
    auth_token:
      secure: 87/CD0OF9Pg6MjGoZ2cNhxpVZkFzTlZ0aL3FGPA3I7YrMdZLEvJKyMq8KzrmNm3W
    on:
      APPVEYOR_REPO_TAG: true